const link = {
    base: 'http://49.50.164.23',
    home: '/',
    defaultcloset: '/closet',
    closet: '/closet/:category',
    detailcoordination: '/closet/coordination/:id',
    defaultproduct: '/product',
    product: '/product/:category/:subcategory',
    detailproduct: '/product/:id',
    account: '/account',
    signin: '/account/signin',
    findid: '/account/findid',
    findpw: '/account/findpw',
    findpwemail: '/account/findpwemail',
    register: '/account/register',
    afterregister: '/account/afterregister',
    detailinfo: '/account/detailinfo',
    info: '/account/info',
    style: '/account/style',
    order: '/account/order',
    feedback: '/account/feedback',
    cart: '/cart',
    article: '/article',
    detailarticle: '/article/:id',
    about: '/about',
    faq: "/about/faq",
    chatting: "/about/chatting",
    privacy: "/about/policy",
    terms: "/about/terms",
}
export default link