const link = {
    home: '/',
    closet: '/closet',
    product: '/product',
    account: '/account',
    signin: '/account/signin',
    logout: '/accout/logout',
    signup: '/account/signup',
    findid: '/account/findid',
    findpw: '/account/findpw',
    findpwemail : '/account/findpwemail',
    register: '/account/register',
    info: '/account/info',
    style: '/account/style',
    order: '/account/order',
    feedback: '/account/feedback',
    cart: '/cart',
    article: '/article',
    about: '/about',
    faq: "/about/faq",
    chatting: "/about/chatting",
    privacy: "/about/policy",
    terms: "/about/terms",
}
export default link