const Category = {
    "outer": 1,
    "top": 2,
    "bottom":3,
    "skirt": 4,
    "set": 5,
    "shoes": 6,
    "bag": 7,
    "hat": 8,

}

const SubCategory = {
    "all": -1,
    "coat" : 1,
    "padding": 2,
    "cardigan" : 4,
    "blazer" : 8,
    "jumper": 16,
    "jacket" : 32,
    "hoodzipup": 64,
    "fleece": 128,
    "tshirt": 1,
    "shirts" : 2,
    "longsleeve": 4,
    "sweatshirt": 8,
    "hoodie": 16,
    "knit": 32,
    "sleeveless": 64,
    "vest": 128,
    "jeans": 1,
    "slacks": 2,
    "cotton": 4,
    "training": 8,
    "jogger": 16,
    "shorts": 32,
    "leggings": 64,
    "mini": 1,
    "middle": 2,
    "long": 4,
    "onepiece": 1,
    "twopiece": 2,
    "suit": 4,
    "jumpsuit": 8,
    "sneakers": 1,
    "roper": 2,
    "boots": 4,
    "derby": 8,
    "heels": 16,
    "sandals": 32,
    "slippers": 64,
    "backpack": 1,
    "massenger": 2,
    "dot": 4,
    "eco": 8,
    "leather": 16,
    "cap": 1,
    "beanie": 2,
    "bucket": 4,
    "beret": 8,
}

const NumToStringStyle = {
    1: "minimal",
    2: "casual",
    4: "campus",
    8: "street",
    16: "rock_chic",
    32: "amekaji",
    64: "city_boy",
    128: "office",
    256: "sexy_glam",
    512: "feminine",
    1024: "lovely"
}

export { Category, SubCategory, NumToStringStyle }