const string = {
	en: {
		api_title: "Gets: API",
		api_sign: "Sign in/up",
		api_sign_in: "Sign in",
		api_sign_up: "Sign up",
		api_sign_up_basic: "Sign up - basic",
		api_sign_up_info: "Sign up - info",
		api_sign_up_check: "Sign up - check id",
		api_user: "User",
		api_weather: "Weather",
		api_product: "Product",
		api_product_image: "Product - image",
		api_product_list: "Product - list",
		api_product_list_page: "Product - list by page",
		api_product_toptrend: "Product - toptrend",
		api_product_favorite: "Product - favorite",
		api_product_unfavorite: "Product - unfavorite",
		api_product_count_favorite: "Product - favorite count",
		api_review_add: "Review - add",
		api_review_fit: "Review -fit",
		api_review: "Review - list",
		api_coordination: "Coordination",
		api_coordination_image: "Coordination - image",
		api_coordination_anything: "Coordination - anything",
		api_coordination_style: "Coordination - style",
		api_coordination_represent: "Coordination - representative",
		api_coordination_favorite: "Coordination - favorite",
		api_coordination_unfavorite: "Coordination - unfavorite",
		api_coordination_count_favorite: "Coordination - favorite count",
		api_closet: "Closet",
		api_closet_product: "Closet - product list",
		api_closet_coordination: "Closet - coordination list",
	},
	ko: {
		api_title: "Gets: API",
		api_sign: "로그인/회원가입",
		api_sign_in: "로그인",
		api_sign_up: "회원가입",
		api_sign_up_basic: "회원가입 - 기본",
		api_sign_up_info: "회원가입 - 추가 정보",
		api_sign_up_check: "회원가입 - ID 중복 확인",
		api_user: "사용자",
		api_weather: "날씨",
		api_product: "상품",
		api_product_image: "상품 - 이미지",
		api_product_list: "상품 - 목록",
		api_product_list_page: "상품 - 페이지별 목록",
		api_product_toptrend: "상품 - 탑트랜드",
		api_product_favorite: "상품 - 찜하기",
		api_product_unfavorite: "상품 - 찜취소",
		api_product_count_favorite: "상품 - 찜개수",
		api_review_add: "리뷰 - 추가",
		api_review_fit: "리뷰 - 맞춤",
		api_review: "리뷰 - 리스트",
		api_coordination: "코디",
		api_coordination_image: "코디 - 이미지",
		api_coordination_anything: "코디 - 랜덤",
		api_coordination_style: "코디 - 스타일",
		api_coordination_represent: "코디 - 대표",
		api_coordination_favorite: "코디 - 찜하기",
		api_coordination_unfavorite: "코디 - 찜취소",
		api_coordination_count_favorite: "코디 - 찜개수",
		api_closet: "옷장",
		api_closet_product: "옷장 - 제품 리스트",
		api_closet_coordination: "옷장 - 코디 리스트",
	}
}

module.exports = string