const string = {
	en: {
		title: "Gets",
		main_title: "Gets: Custom Fashion Platform",
		select_style: "#Select your style",
		recommend_style: "#Recommend style",
		select_info: "#About",
		gender: "GENDER",
		age: "AGE",
		body_type: "BODY TYPE",
		fit: "FIT",
		price: "PRICE",
		woman: "woman",
		man: "man",
		age_10: "10s",
		age_20: "20s",
		age_30: "30s",
		age_40: "40s",
		age_50: "50s ~",
		lower_body_fat: "chubby lower body",
		upper_body_fat: "chubby upper body",
		slim: "slim",
		tall: "tall",
		short: "short",
		style_minimal: "Minimal",
		style_casual: "Casual",
		style_campus: "Campus",
		style_office: "Office",
		style_rock_chic: "Rock chic",
		style_street: "Street",
		style_amekaji: "Amekaji",
		style_city_boy: "City boy",
		style_feminine: "Feminine",
		style_lovely: "Lovely",
		style_sexy_glam: "Sexy glam",
		fit_regular: "regular",
		fit_over: "over",
		fit_wide: "wide",
		fit_semi_wide: "semi wide",
		fit_straight: "straight",
		fit_slim: "slim",
		fit_tapered: "tapered",
		fit_bootcut: "bootcut",
		price_100000: "~ 100000 won",
		price_200000: "~ 200000 won",
		price_300000: "~ 300000 won",
		price_400000: "~ 400000 won",
		price_500000: "~ 500000 won",
		price_expensive: "500000 won ~",
	},
	ko: {
		title: "Gets",
		main_title: "Gets: 맟춤형 패션 플랫폼",
		select_style: "#취향 선택",
		recommend_style: "#추천 코디",
		select_info: "#About",
		gender: "성별",
		age: "연령",
		body_type: "체형",
		fit: "핏",
		price: "가격",
		woman: "여자",
		man: "남자",
		age_10: "10대",
		age_20: "20대",
		age_30: "30대",
		age_40: "40대",
		age_50: "50대 이상",
		lower_body_fat: "하체 통통",
		upper_body_fat: "상체 통통",
		slim: "마른",
		tall: "키 큰",
		short: "키 작은",
		style_minimal: "Minimal",
		style_casual: "Casual",
		style_campus: "Campus",
		style_office: "Office",
		style_rock_chic: "Rock chic",
		style_street: "Street",
		style_amekaji: "Amekaji",
		style_city_boy: "City boy",
		style_feminine: "Feminine",
		style_lovely: "Lovely",
		style_sexy_glam: "Sexy glam",
		fit_regular: "레귤러",
		fit_over: "오버핏",
		fit_wide: "와이드",
		fit_semi_wide: "세미 와이드",
		fit_straight: "스트레이트",
		fit_slim: "슬림",
		fit_tapered: "테이퍼드",
		fit_bootcut: "부츠컷",
		price_100000: "10만원 이하",
		price_200000: "20만원 이하",
		price_300000: "30만원 이하",
		price_400000: "40만원 이하",
		price_500000: "50만원 이하",
		price_expensive: "50만원 이상",
	}
}

module.exports = string